name: Test Contracts

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize]

jobs:
  test-contracts:
    runs-on: ubuntu-latest
    container: node:16

    env:
      FORCE_COLOR: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cacheh: 'yarn'

      - run: yarn install
      - run: yarn workspace @discovery-dao/contracts compile
      - run: yarn workspace @discovery-dao/contracts lint
      - run: yarn workspace @discovery-dao/contracts test
