name: Web-app - Test Suite

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"
          registry-url: "https://npm.pkg.github.com"

      - name: Setup module dependencies cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install module dependencies
        run: yarn install --frozen-lockfile

      - name: Lint next
        run: yarn workspace @discovery-dao/web-app lint:next

      - name: Generate wagmi
        run: yarn workspace @discovery-dao/contracts wagmi:generate
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

      - name: Lint types
        run: yarn workspace @discovery-dao/web-app lint:tsc

      - name: Build
        run: yarn workspace @discovery-dao/web-app build
        env:
          NEXT_PUBLIC_WC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WC_PROJECT_ID }}
          NEXT_CITIZEND_WALLET_PRIVATE_KEY: ${{ secrets.NEXT_CITIZEND_WALLET_PRIVATE_KEY }}
          NEXT_PUBLIC_IDOS_NODE_URL: ${{ secrets.NEXT_PUBLIC_IDOS_NODE_URL }}
          NEXT_CITIZEND_ENCRYPTION_SECRET_KEY: ${{ secrets.NEXT_CITIZEND_ENCRYPTION_SECRET_KEY }}
